# -*- coding: utf-8 -*-
"""automate_AdityaWisnu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1RS1nc6b3ENpQH_s__HeiRteWP6K7g0
"""

import pandas as pd
import numpy as np
import os
import shutil
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from google.colab import files  # Khusus Colab

def load_data(path):
    if not os.path.exists(path):
        raise FileNotFoundError(f"File tidak ditemukan di: {path}")
    return pd.read_csv(path)

def preprocess_data(df):
    """
    Logika Preprocessing standar
    """
    # 1. Hapus Duplikat
    df = df.drop_duplicates()

    # 2. Cek Target
    target_col = 'HeartDisease'
    if target_col not in df.columns:
        raise ValueError(f"Kolom target '{target_col}' tidak ditemukan.")

    X = df.drop(target_col, axis=1)
    y = df[target_col]

    # 3. Definisi Fitur
    cat_features = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']
    num_features = ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak']

    # 4. Pipeline Transformer
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), num_features),
            ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), cat_features)
        ],
        remainder='passthrough'
    )

    # 5. Eksekusi
    X_processed = preprocessor.fit_transform(X)

    # Kembalikan Nama Kolom
    ohe_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(cat_features)
    new_columns = num_features + list(ohe_feature_names)

    X_df = pd.DataFrame(X_processed, columns=new_columns)

    return X_df, y

def main():
    print("="*50)
    print("   OTOMATISASI PREPROCESSING (GOOGLE COLAB VERSION)")
    print("="*50)

    # --- KONFIGURASI PATH COLAB ---
    base_dir = '/content'
    input_filename = 'heart.csv'
    input_path = os.path.join(base_dir, input_filename)
    output_dir = os.path.join(base_dir, 'heart_failure_preprocessing')

    # 1. CEK FILE INPUT
    if not os.path.exists(input_path):
        print(f"[ERROR] File '{input_filename}' belum di-upload!")
        print("Silakan upload file heart.csv ke menu Files (ikon folder) di sebelah kiri.")
        return

    print(f"[INFO] File ditemukan: {input_path}")

    # 2. LOAD & PREPROCESS
    try:
        df = load_data(input_path)
        print(f"[INFO] Dataset dimuat. Shape awal: {df.shape}")

        print("[INFO] Melakukan preprocessing...")
        X, y = preprocess_data(df)
        print(f"[INFO] Preprocessing selesai. Shape fitur: {X.shape}")

        # 3. SPLIT DATA
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        # 4. SIMPAN HASIL
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            print(f"[INFO] Membuat folder output: {output_dir}")

        X_train.to_csv(os.path.join(output_dir, 'X_train.csv'), index=False)
        X_test.to_csv(os.path.join(output_dir, 'X_test.csv'), index=False)
        y_train.to_csv(os.path.join(output_dir, 'y_train.csv'), index=False)
        y_test.to_csv(os.path.join(output_dir, 'y_test.csv'), index=False)

        print(f"[SUCCESS] 4 File CSV berhasil disimpan di {output_dir}")

        # 5. ZIP & DOWNLOAD OTOMATIS (Supaya mudah diambil)
        print("[INFO] Membuat file ZIP untuk didownload...")
        shutil.make_archive('/content/hasil_preprocessing', 'zip', output_dir)

        print("[INFO] Mengunduh ke komputer Anda...")
        files.download('/content/hasil_preprocessing.zip')

    except Exception as e:
        print(f"[ERROR] Terjadi kesalahan: {e}")

if __name__ == "__main__":
    main()